apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devsu-hpa
  namespace: devsu  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment         
    name: devsu-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
